version: '3.9'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    container_name: reverse-proxy
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --log.level=DEBUG
      - --providers.docker
      - --providers.docker.network=web
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http
      - --certificatesresolvers.letsencrypt.acme.email=johan.van.der.heide@itea4.org
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entrypoint.to=https
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls=true
      - --entrypoints.https.http.tls.certResolver=letsencrypt
      - --entrypoints.https.http.tls.domains[0].main=eurekaclusters.eu
      - --entrypoints.https.http.tls.domains[1].main=api.eurekaclusters.eu
    restart: always
    networks:
      web: { }
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/letsencrypt

  webserver:
    image: ghcr.io/eureka-clusters/backend/webserver:latest
    container_name: webserver
    volumes:
      - './.docker/nginx/conf.d:/etc/nginx/conf.d'
    labels:
      - traefik.enable=true
      - traefik.http.services.webserver.loadbalancer.server.port=80
      - traefik.http.routers.webserver.service=webserver
      - traefik.http.routers.webserver.rule=Host(`api.eurekaclusters.eu`)
      - traefik.http.routers.webserver.entrypoints=https
      - traefik.http.routers.webserver.tls=true
    restart: always
    networks:
      - internal
      - web

  app:
    image: ghcr.io/eureka-clusters/backend/app:latest
    container_name: app
    labels:
      - traefik.enable=false
    volumes:
      - ./conf/doctrine_orm.global.php:/var/www/config/autoload/doctrine_orm.global.php
      - ./conf/oauth2.services.global.php:/var/www/config/autoload/oauth2.services.global.php
    restart: always
    networks:
      - internal

  portal:
    image: ghcr.io/eureka-clusters/frontend:latest
    container_name: portal
    labels:
      - traefik.enable=true
      - traefik.http.services.portal.loadbalancer.server.port=80
      - traefik.http.routers.portal-https.service=portal
      - traefik.http.routers.portal-https.rule=Host(`eurekaclusters.eu`)
      - traefik.http.routers.portal-https.entrypoints=https
      - traefik.http.routers.portal-https.tls=true
    restart: always
    networks:
      - web

  redis:
    image: redis:latest
    container_name: pa-portal-redis
    restart: always
    labels:
      - traefik.enable=false
    networks:
      - internal

volumes:
  certs:

networks:
  web:
    external: true
  internal:
    external: false