version: '3.9'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    container_name: reverse-proxy
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --log.level=INFO
      - --api.insecure=true
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --providers.docker
      - --providers.docker.network=web
      - --providers.docker.defaultRule=Host(`eurekaclusters.eu`)
    networks:
      web: { }
    ports:
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    image: ghcr.io/eureka-clusters/portal-backend/backend:main
    container_name: backend
    labels:
      - traefik.enable=true
      - traefik.https.services.backend.loadbalancer.server.port=80
      - traefik.https.routers.backend-https.service=backend
      - traefik.https.routers.backend-https.rule=Host(`api.eurekaclusters.eu`)
      - traefik.https.routers.backend-https.entrypoints=websecure
    networks:
      - web

  portal:
    image: ghcr.io/eureka-clusters/pa-portal/pa-portal:migration-to-typescript
    container_name: portal
    labels:
      - traefik.enable=true
      - traefik.https.services.portal.loadbalancer.server.port=80
      - traefik.https.routers.portal-https.service=portal
      - traefik.https.routers.portal-https.rule=Host(`eurekaclusters.eu`)
      - traefik.https.routers.portal-https.entrypoints=websecure
    networks:
      - web

networks:
  web:
    external: true